fix: improved `keyPath`/`keyPair` error handling
As proposed by @pzhlkj6612 in #12:
- do not output error if no key path was specified
- cleaner error output

Unlike in proposal, this change does not change API:
- function names stay the same
- no exceptions are thrown

Example without path to key file:

```sh
> ./bin/crx3.js ./example/example-extension

No `keyPath` was specified. Private key will not be saved to a file.
CRX file created at "/app/example-extension.crx"
```

With path to non-existing key file:

```sh
> ./bin/crx3.js ./example/example-extension -p ./new-key.pem

Private key file created at "/app/new-key.pem"
CRX file created at "/app/example-extension.crx"
```

With path to existing but invalid key file:
```sh
> ./bin/crx3.js ./example/example-extension -p ./invalid-key.pem

"/app/invalid-key.pem" already exists but could not be loaded.
Error: error:1E08010C:DECODER routines::unsupported
    at Object.createPrivateKey (node:internal/crypto/keys:632:12)
    at tryLoadKeyPair (/app/lib/keypair.js:74:23)
    at createKeyPair (/app/lib/keypair.js:49:16)
    at CRX3Stream.crxInit (/app/lib/crx3stream.js:126:19)
    at CRX3Stream._write (/app/lib/crx3stream.js:86:9)
    at doWrite (node:internal/streams/writable:411:12)
    at clearBuffer (node:internal/streams/writable:572:7)
    at CRX3Stream.<anonymous> (node:internal/streams/writable:264:7)
    at Object.onceWrapper (node:events:627:28)
    at CRX3Stream.emit (node:events:513:28) {
  library: 'DECODER routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_UNSUPPORTED'
}
CRX3 requires valid private key
```